---
all:
  children:
    dbservers:
      hosts:
        db01:
          ansible_host: 192.168.2.174
    webservers:
      hosts:
        db01:
    k8s_cluster:
      children:
        k8s_control_plane:
          hosts:
            master:
              ansible_host: 192.168.2.176
        k8s_workers:
          hosts:
            kube01:
              ansible_host: 192.168.2.178
            kube02:
              ansible_host: 192.168.2.180
